hajonsoft/hajonsoft-tiger

src/features/Dashboard/index.js

Filter expired passports for hajj mission of cote de ivoir. This feature is a quick and dirty fix for brother ouattara requirement

feat(HS-167): filter expired passports

---

.github/PULL_REQUEST_TEMPLATE.md
package-lock.json
package.json
src/features/Dashboard/index.js

feat(DSK-109): fix filtered travellers

---

README.md

Update readme with information about slack recurring message for virtual standup

fix: slack reminder

---

.github/PULL_REQUEST_TEMPLATE.md
src/App.js
src/features/Dashboard/components/ApplyForVisa.js
src/features/Dashboard/components/packageDetail.js
src/features/Dashboard/index.js
src/features/Dashboard/redux/travellerService.js
src/features/Profile/index.js
src/features/SignIn/SignIn.js
src/features/onlinePackage/components/PackageSchedule.js
src/features/shared/components/AppHeader/AppHeader.js
src/redux/reducer.js
src/redux/saga.js

add progress indicator when downloading travellers json file, rename groups to caravans

feat: select travelers, rename to caravan

---

src/features/Dashboard/components/ApplyForVisa.js

add hawk links in apply for visa

feat: hawk links

---

src/features/help/helpCard.js
src/features/help/index.js

feat: helpcards

---

src/features/Dashboard/components/ApplyForVisa.js
src/features/help/index.js

Add link to take course. correct typos in assistance spicework flow

feat: take course

---

.vscode/bookmarks.json
database.rules.json
database.rules.template.json
src/features/Dashboard/components/ApplyForVisa.js
users

feat: visa by proxy email

---

.vscode/bookmarks.json
src/features/Dashboard/redux/useTravellerState.js
src/features/Reservation/index.js
src/features/customer/components/CRUDForm.js

feat: show reservation name

---

src/features/Dashboard/components/ApplyForVisa.js
src/features/Dashboard/components/packageDetail.js
src/features/Dashboard/index.js
src/features/customer/components/CRUDForm.js

rename traveller to passenger everywhere

---

.vscode/bookmarks.json
src/features/Dashboard/helpers/common.js
src/util/codeline.js

add vaccine

---

src/features/Dashboard/components/ApplyForVisa.js
src/features/Dashboard/helpers/common.js

feat: export vacchine

---

src/util/codeline.js

fix codeline generation, it turns out we were not calculating check digit for expire date and the filler

fix: codline gneration

---

src/features/Reservation/index.js
src/features/onlineCaravan/components/AdvertisementDetail.js

add description to learn more

---

src/features/Dashboard/index.js

merge caravans

---

src/features/Dashboard/components/IDCard.js

comment image in ID card

---

package-lock.json
package.json
src/features/Dashboard/components/ApplyForVisa.js
src/features/Dashboard/components/IDCard.js
src/features/Dashboard/components/Table.js
src/features/passengers/components/CRUDForm.js
src/lang/ar.json
src/lang/en.json
src/lang/fr.json

Smart form

---

src/features/Dashboard/components/EmbassyReports.js
src/features/Dashboard/components/IDCard.js
src/features/Dashboard/components/Table.js

format report dates

---

src/features/Dashboard/components/packageDetail.js
src/features/Dashboard/redux/caravanSlice.js
src/features/Dashboard/redux/pastCaravanSlice.js
src/features/passengers/components/CustomerDetail.js
src/features/passengers/index.js
src/redux/helpers.js

move passenger

---

src/features/Dashboard/components/EmbassyReports.js
src/features/Dashboard/components/packageDetail.js
src/firebaseConfig.js
src/shared/util/formatPassengers.js

formatPassengers

---

src/features/Dashboard/components/IDCard.js

fix last name

---

src/features/Reservation/components/FullReservation.js
src/features/Reservation/components/InputControl.js
src/firebaseConfig.js
src/shared/macaw/AppHeader.js
src/theme/default.js
src/theme/lake.js

Reservation scroll

---

src/features/Dashboard/index.js
src/features/Dashboard/redux/caravanSlice.js
src/features/passengers/index.js
src/redux/helpers.js
src/shared/macaw/AppHeader.js
src/workers/parser.worker.js

global search

---

src/features/Dashboard/components/EmbassyReports.js
src/features/Dashboard/components/Table.js
src/features/Dashboard/components/table.module.css
src/features/Dashboard/redux/caravanSlice.js
src/features/passengers/components/CRUDForm.js
src/redux/helpers.js
src/shared/macaw/CoreImage.js
src/shared/util/formatPassengers.js
yarn.lock

download all photos on caravan load

---

src/features/BulkUpload/index.js
src/features/Dashboard/redux/caravanSlice.js
src/features/onlineCaravan/components/AdvertisementCard.js
src/features/onlineCaravan/redux/onlineCaravanSlice.js
src/features/passengers/components/Passenger.js
src/features/passengers/index.js

initial files

---

src/features/Caravans/helpers/common.js
src/features/passengers/components/Passenger.js
src/shared/macaw/CoreImage.js
src/shared/macaw/CorePassportImage.js
src/shared/macaw/CoreVaccineImage.js

additional photos and idNumber

---

src/workers/parser.worker.js

fix germany parsing

---

src/features/Caravans/index.js

remove merge click

---

src/features/Caravans/components/PrintableTable.js
src/features/Caravans/components/Table.js

Add right to left functionality to table when user language is arabic

Arabic-report-rtl
